# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
# Changed from 2.0 to 2.1 so orbs can be used.
version: 2.0
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/pokt-network/pocket-core
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: ./deps.sh
      - run: go build cmd/pocket_core/main.go
      - run: go test ./tests/unit/...
      - run: go test ./tests/bdd/...
  deployment_build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          name: Trigger Pocket Core Deployment build.
          command: "curl -u ${CIRCLE_API_USER_TOKEN}: -X POST -H \"Content-Type: application/json\" \
          -d \"'{
            \"parameters\":{
              \"BRANCH_NAME\":\"${CIRCLE_BRANCH}\"
              }
            }'\"
          https://circleci.com/api/v2/project/github/pokt-network/pocket-core-deployments/pipeline "
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deployment_build